steps:
  # Paso 1: Construir la imagen del contenedor del frontend con Nginx y Dockerfile.prod
  # Se inyecta la URL del backend de producción usando el build-arg VITE_API_URL
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'frontend'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.prod'
      - '-t'
      - 'gcr.io/$PROJECT_ID/frontend:$_COMMIT_SHA'
      - '--build-arg'
      - 'VITE_API_URL=https://backend-337307900667.southamerica-west1.run.app'
      - '.'

  # Paso 2: Subir la imagen a Artifact Registry / Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend:$_COMMIT_SHA']

  # Paso 3: Desplegar el frontend en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'frontend'
      - '--image=gcr.io/$PROJECT_ID/frontend:$_COMMIT_SHA'
      - '--region=southamerica-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/frontend:$_COMMIT_SHA'

substitutions:
  _COMMIT_SHA: 'latest'

options:
  logging: CLOUD_LOGGING_ONLY
