# --- Etapa 1: Construcción (Build) ---
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

# Definir el build argument para inyectar la URL del backend durante la compilación
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

COPY . .
RUN npm run build

# --- Etapa 2: Servidor de Producción (Nginx) ---
FROM nginx:stable-alpine

# Copiar la configuración personalizada de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiar los archivos compilados de React a la carpeta de Nginx
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
