services:
  # Servicio Proxy oficial para conectar a Cloud SQL en GCP
  cloud-sql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
    container_name: cloud_sql_proxy
    user: root
    restart: always
    command:
      - "--address=0.0.0.0"
      - "--port=5432"
      - "${INSTANCE_CONNECTION_NAME}"
    volumes:
      - ~/.config/gcloud:/config/gcloud:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/config/gcloud/application_default_credentials.json
    ports:
      - "5433:5432" # Expuesto a la máquina host (ej. para DBeaver, pg_dump, etc.)

  backend:
    build: ./backend
    container_name: django_backend
    image: joseveloso/ecommerce_apicultura-backend:v1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - ~/.config/gcloud:/root/.config/gcloud:ro
    ports:
      - "8080:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - cloud-sql-proxy
    environment:
      - DEBUG=${DEBUG:-1}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME:-postgres}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST:-cloud-sql-proxy}
      - DB_PORT=${DB_PORT:-5432}
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:5173}

  frontend:
    build: 
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    
    environment:
      #- VITE_API_URL=https://backend-337307900667.southamerica-west1.run.app
      - VITE_API_URL=http://localhost:8080

    depends_on:
      - backend

# volumes:
#   pgdata:
