--
-- PostgreSQL database dump
--

\restrict NDmkMj4xtp4iAhlMvdWj4tDm3emcvrS2AjbQFd5MCgYtQy8SStMgjlkdEE5fNFc

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: productos_carritoitem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.productos_carritoitem (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    producto_id bigint NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT productos_carritoitem_cantidad_check CHECK ((cantidad >= 0))
);


--
-- Name: productos_carritoitem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.productos_carritoitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_carritoitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productos_categoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.productos_categoria (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text
);


--
-- Name: productos_categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.productos_categoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productos_cupon; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.productos_cupon (
    id bigint NOT NULL,
    codigo character varying(50) NOT NULL,
    descuento_porcentaje integer NOT NULL,
    descuento_valor numeric(10,2) NOT NULL,
    activo boolean NOT NULL,
    CONSTRAINT productos_cupon_descuento_porcentaje_check CHECK ((descuento_porcentaje >= 0))
);


--
-- Name: productos_cupon_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.productos_cupon ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_cupon_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productos_galeria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.productos_galeria (
    id bigint NOT NULL,
    imagen character varying(100) NOT NULL,
    caption text,
    likes integer NOT NULL,
    comments integer NOT NULL,
    link character varying(200) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT productos_galeria_comments_check CHECK ((comments >= 0)),
    CONSTRAINT productos_galeria_likes_check CHECK ((likes >= 0))
);


--
-- Name: productos_galeria_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.productos_galeria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_galeria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productos_itempedido; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.productos_itempedido (
    id bigint NOT NULL,
    nombre_producto character varying(200) NOT NULL,
    precio numeric(10,2) NOT NULL,
    cantidad integer NOT NULL,
    producto_id bigint,
    pedido_id bigint NOT NULL,
    CONSTRAINT productos_itempedido_cantidad_check CHECK ((cantidad >= 0))
);


--
-- Name: productos_itempedido_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.productos_itempedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_itempedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productos_pedido; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.productos_pedido (
    id bigint NOT NULL,
    nombre_completo character varying(255) NOT NULL,
    email character varying(254) NOT NULL,
    telefono character varying(20) NOT NULL,
    direccion character varying(255) NOT NULL,
    ciudad character varying(100) NOT NULL,
    metodo_pago character varying(50) NOT NULL,
    total numeric(10,2) NOT NULL,
    estado character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id integer
);


--
-- Name: productos_pedido_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.productos_pedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productos_perfilusuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.productos_perfilusuario (
    id bigint NOT NULL,
    rut character varying(15),
    telefono character varying(20),
    direccion character varying(255),
    ciudad character varying(100),
    user_id integer NOT NULL
);


--
-- Name: productos_perfilusuario_cupones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.productos_perfilusuario_cupones (
    id bigint NOT NULL,
    perfilusuario_id bigint NOT NULL,
    cupon_id bigint NOT NULL
);


--
-- Name: productos_perfilusuario_cupones_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.productos_perfilusuario_cupones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_perfilusuario_cupones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productos_perfilusuario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.productos_perfilusuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_perfilusuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productos_producto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.productos_producto (
    id bigint NOT NULL,
    nombre character varying(200) NOT NULL,
    descripcion text NOT NULL,
    precio numeric(10,2) NOT NULL,
    stock integer NOT NULL,
    categoria_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    imagen character varying(100),
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT productos_producto_stock_check CHECK ((stock >= 0))
);


--
-- Name: productos_producto_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.productos_producto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_producto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add categoria	7	add_categoria
26	Can change categoria	7	change_categoria
27	Can delete categoria	7	delete_categoria
28	Can view categoria	7	view_categoria
29	Can add producto	8	add_producto
30	Can change producto	8	change_producto
31	Can delete producto	8	delete_producto
32	Can view producto	8	view_producto
33	Can add galeria	9	add_galeria
34	Can change galeria	9	change_galeria
35	Can delete galeria	9	delete_galeria
36	Can view galeria	9	view_galeria
37	Can add Token	10	add_token
38	Can change Token	10	change_token
39	Can delete Token	10	delete_token
40	Can view Token	10	view_token
41	Can add Token	11	add_tokenproxy
42	Can change Token	11	change_tokenproxy
43	Can delete Token	11	delete_tokenproxy
44	Can view Token	11	view_tokenproxy
45	Can add cupon	12	add_cupon
46	Can change cupon	12	change_cupon
47	Can delete cupon	12	delete_cupon
48	Can view cupon	12	view_cupon
49	Can add pedido	13	add_pedido
50	Can change pedido	13	change_pedido
51	Can delete pedido	13	delete_pedido
52	Can view pedido	13	view_pedido
53	Can add item pedido	14	add_itempedido
54	Can change item pedido	14	change_itempedido
55	Can delete item pedido	14	delete_itempedido
56	Can view item pedido	14	view_itempedido
57	Can add perfil usuario	15	add_perfilusuario
58	Can change perfil usuario	15	change_perfilusuario
59	Can delete perfil usuario	15	delete_perfilusuario
60	Can view perfil usuario	15	view_perfilusuario
61	Can add carrito item	16	add_carritoitem
62	Can change carrito item	16	change_carritoitem
63	Can delete carrito item	16	delete_carritoitem
64	Can view carrito item	16	view_carritoitem
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$hqooKSVj0ZE3xLvAYiBuMB$QZm1b3Yakt3hY8qWuSUml+CmXbHvrJnkZ6wovUoKFQs=	2025-10-09 06:54:51.744938+00	t	jose			joseveloso2101@gmail.com	t	t	2025-10-06 22:05:35.966726+00
2	pbkdf2_sha256$1000000$ipSuSRgxNtXEftGcqGwabV$BdIbXmZEInVlQt5+UJPGgC1PySUydxS3thvfQK+0m4I=	2026-06-13 10:10:57.689601+00	t	admin			joseveloso2101@gmail.com	t	t	2026-06-12 23:56:48.870312+00
3	pbkdf2_sha256$1000000$DnmHs4L0H5YZemwqWOrV5a$K2lw21vLvhUl7mznVNXmTh2NVg+FSPHWRJKQWBjG9Vc=	\N	f	josevin09@gmail.com	Jose	Veloso Inzunza	josevin09@gmail.com	f	t	2026-06-26 06:59:07.620544+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.authtoken_token (key, created, user_id) FROM stdin;
e4d58ed47f5d6fc2b502f7e6bf9ea6a772e9964b	2026-06-26 06:59:07.844765+00	3
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-10-08 22:01:35.657419+00	1	Alimentos	1	[{"added": {}}]	7	1
2	2025-10-08 22:01:40.645121+00	1	Miel Multifloral 1000g	1	[{"added": {}}]	8	1
3	2025-10-09 06:55:12.532209+00	1	Miel Multifloral 1000g	3		8	1
4	2026-06-12 23:59:38.988931+00	2	Miel 1 Kg	1	[{"added": {}}]	8	2
5	2026-06-13 00:11:12.710822+00	2	Miel 1 Kg	2	[{"changed": {"fields": ["Imagen"]}}]	8	2
6	2026-06-13 00:15:40.156149+00	2	Medicinas	1	[{"added": {}}]	7	2
7	2026-06-13 00:21:33.989049+00	3	Subproductos	1	[{"added": {}}]	7	2
8	2026-06-13 00:22:03.882629+00	4	Insumos	1	[{"added": {}}]	7	2
9	2026-06-13 00:23:27.16737+00	5	Material biológico	1	[{"added": {}}]	7	2
10	2026-06-13 09:23:14.729905+00	2	Miel 1 Kg	2	[]	8	2
11	2026-06-13 09:48:55.306514+00	2	Miel 1 Kg	2	[{"changed": {"fields": ["Imagen"]}}]	8	2
12	2026-06-13 09:49:48.475391+00	2	Miel 1 Kg	2	[{"changed": {"fields": ["Imagen"]}}]	8	2
13	2026-06-14 04:59:27.330874+00	2	Miel 1 Kg	2	[{"changed": {"fields": ["Descripcion"]}}]	8	2
14	2026-06-14 05:28:36.557353+00	3	Miel 500 g	1	[{"added": {}}]	8	2
15	2026-06-14 05:30:40.369249+00	4	Miel 265 g	1	[{"added": {}}]	8	2
16	2026-06-14 05:38:30.224892+00	5	Propoleo en gotas 15 mL	1	[{"added": {}}]	8	2
17	2026-06-15 02:28:51.795263+00	6	Miel en panal 200 g	1	[{"added": {}}]	8	2
18	2026-06-15 02:29:18.665495+00	6	Miel en panal 200 g	2	[{"changed": {"fields": ["Imagen"]}}]	8	2
19	2026-06-15 21:50:22.161785+00	2	Medicinas	2	[{"changed": {"fields": ["Descripcion"]}}]	7	2
20	2026-06-15 21:50:27.708194+00	4	Insumos	2	[{"changed": {"fields": ["Descripcion"]}}]	7	2
21	2026-06-15 21:50:34.043844+00	5	Material biológico	2	[{"changed": {"fields": ["Descripcion"]}}]	7	2
22	2026-06-15 21:50:41.325996+00	1	Alimentos	2	[{"changed": {"fields": ["Descripcion"]}}]	7	2
23	2026-06-15 21:57:46.271574+00	7	Caballete o base	1	[{"added": {}}]	8	2
24	2026-06-15 22:02:07.236051+00	8	Cámara de cria	1	[{"added": {}}]	8	2
25	2026-06-15 22:02:55.347845+00	8	Cámara de cria	2	[{"changed": {"fields": ["Stock"]}}]	8	2
26	2026-06-15 22:08:03.733518+00	7	Caballete o base	2	[{"changed": {"fields": ["Stock"]}}]	8	2
27	2026-06-15 22:08:15.001783+00	6	Miel en panal 200 g	2	[{"changed": {"fields": ["Stock"]}}]	8	2
28	2026-06-15 22:08:25.237328+00	5	Propoleo en gotas 15 mL	2	[{"changed": {"fields": ["Stock"]}}]	8	2
29	2026-06-15 22:08:44.853238+00	2	Miel 1 Kg	2	[{"changed": {"fields": ["Stock"]}}]	8	2
30	2026-06-15 22:09:01.707706+00	3	Miel 500 g	2	[{"changed": {"fields": ["Stock"]}}]	8	2
31	2026-06-15 22:09:08.692224+00	4	Miel 265 g	2	[{"changed": {"fields": ["Stock"]}}]	8	2
32	2026-06-17 22:29:26.802196+00	2	Miel 1 Kg	2	[{"changed": {"fields": ["Stock"]}}]	8	2
33	2026-06-25 21:20:22.065258+00	7	Caballete o base	2	[]	8	2
34	2026-06-25 21:20:30.375115+00	7	Caballete o base	2	[{"changed": {"fields": ["Imagen"]}}]	8	2
35	2026-06-25 21:20:52.77281+00	7	Caballete o base	2	[{"changed": {"fields": ["Imagen"]}}]	8	2
36	2026-06-25 21:43:32.195877+00	8	Cámara de cria	2	[{"changed": {"fields": ["Imagen"]}}]	8	2
37	2026-06-25 21:44:04.639899+00	8	Cámara de cria	2	[{"changed": {"fields": ["Imagen"]}}]	8	2
38	2026-06-25 23:48:32.807813+00	2	Miel 1 Kg	2	[{"changed": {"fields": ["Imagen"]}}]	8	2
39	2026-06-25 23:49:13.255372+00	2	Miel 1 Kg	2	[{"changed": {"fields": ["Imagen"]}}]	8	2
40	2026-06-26 17:44:54.554305+00	2	Post - 2	1	[{"added": {}}]	9	2
41	2026-06-26 19:50:33.052768+00	2	avellano	2	[{"changed": {"fields": ["Caption", "Link"]}}]	9	2
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	productos	categoria
8	productos	producto
9	productos	galeria
10	authtoken	token
11	authtoken	tokenproxy
12	productos	cupon
13	productos	pedido
14	productos	itempedido
15	productos	perfilusuario
16	productos	carritoitem
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-10-06 22:04:45.749759+00
2	auth	0001_initial	2025-10-06 22:04:45.789704+00
3	admin	0001_initial	2025-10-06 22:04:45.798034+00
4	admin	0002_logentry_remove_auto_add	2025-10-06 22:04:45.801157+00
5	admin	0003_logentry_add_action_flag_choices	2025-10-06 22:04:45.804775+00
6	contenttypes	0002_remove_content_type_name	2025-10-06 22:04:45.812551+00
7	auth	0002_alter_permission_name_max_length	2025-10-06 22:04:45.816581+00
8	auth	0003_alter_user_email_max_length	2025-10-06 22:04:45.820669+00
9	auth	0004_alter_user_username_opts	2025-10-06 22:04:45.825556+00
10	auth	0005_alter_user_last_login_null	2025-10-06 22:04:45.830023+00
11	auth	0006_require_contenttypes_0002	2025-10-06 22:04:45.830663+00
12	auth	0007_alter_validators_add_error_messages	2025-10-06 22:04:45.833813+00
13	auth	0008_alter_user_username_max_length	2025-10-06 22:04:45.839802+00
14	auth	0009_alter_user_last_name_max_length	2025-10-06 22:04:45.843902+00
15	auth	0010_alter_group_name_max_length	2025-10-06 22:04:45.847731+00
16	auth	0011_update_proxy_permissions	2025-10-06 22:04:45.850915+00
17	auth	0012_alter_user_first_name_max_length	2025-10-06 22:04:45.855206+00
18	productos	0001_initial	2025-10-06 22:04:45.868436+00
19	sessions	0001_initial	2025-10-06 22:04:45.874627+00
20	productos	0002_producto_created_at_producto_imagen_and_more	2026-06-13 00:10:23.822944+00
21	productos	0003_galeria	2026-06-24 03:48:13.802308+00
22	authtoken	0001_initial	2026-06-26 05:59:29.262218+00
23	authtoken	0002_auto_20160226_1747	2026-06-26 05:59:29.275264+00
24	authtoken	0003_tokenproxy	2026-06-26 05:59:29.276432+00
25	authtoken	0004_alter_tokenproxy_options	2026-06-26 05:59:29.278124+00
26	productos	0004_cupon_pedido_itempedido_perfilusuario	2026-06-26 05:59:29.313956+00
27	productos	0005_carritoitem	2026-06-26 08:23:28.195676+00
28	productos	0006_alter_galeria_link	2026-06-26 19:48:12.729661+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
09vfogv1k524wcx4yspcegvxmmxl63ly	.eJxVjDsOwjAQBe_iGln-fyjpOYO13rVxADlSnFSIu0OkFNC-mXkvlmBbW9pGWdJE7MwkO_1uGfBR-g7oDv02c5z7ukyZ7wo_6ODXmcrzcrh_Bw1G-9aFvAg6mmC9xxqJsCKRsErpqAxqEM77akBpVa2WEYyL0oLLMgeAotj7A9zVN6U:1v5tNo:5rRZEKUYgDipcryDyWE3Ar1P_lRUE8M9sPfKmV0198g	2025-10-20 22:08:40.24697+00
zdmk24r3vqpthiazjp5c0u8gwhe9gfvy	.eJxVjDsOwjAQBe_iGln-fyjpOYO13rVxADlSnFSIu0OkFNC-mXkvlmBbW9pGWdJE7MwkO_1uGfBR-g7oDv02c5z7ukyZ7wo_6ODXmcrzcrh_Bw1G-9aFvAg6mmC9xxqJsCKRsErpqAxqEM77akBpVa2WEYyL0oLLMgeAotj7A9zVN6U:1v6kY7:-FZkpx4YtQcyeydJVCbu1shL38v6zpG2_HHme9DtFec	2025-10-23 06:54:51.750322+00
bmwhx1efz8x28b1yzprz8q376lyutw3y	.eJxVjDkOwjAUBe_iGlnfSxKHkp4zWH-xcQA5UpxUiLtDpBTQvpl5LxVxW0vcWlriJOqsrDr9boT8SHUHcsd6mzXPdV0m0ruiD9r0dZb0vBzu30HBVr6194TIhIM4jyYHzpyBumRNdjYN6DugUQRsz64PwQhlYAKD5EaSBOr9ARi2OSg:1wYBkK:bNZSyFI8hrMtt73rBJHPqRiNqtH0TJTDvbNNBDr3_8g	2026-06-26 23:57:08.060368+00
2j7i51g1afpg8g65mdv9b1kdqqxt7f3v	.eJxVjDkOwjAUBe_iGlnfSxKHkp4zWH-xcQA5UpxUiLtDpBTQvpl5LxVxW0vcWlriJOqsrDr9boT8SHUHcsd6mzXPdV0m0ruiD9r0dZb0vBzu30HBVr6194TIhIM4jyYHzpyBumRNdjYN6DugUQRsz64PwQhlYAKD5EaSBOr9ARi2OSg:1wYLKL:ng4UVAO8bKjHWkkLYhjX_GmrZxTj4FTpeXXUUpB4T4I	2026-06-27 10:10:57.691341+00
\.


--
-- Data for Name: productos_carritoitem; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.productos_carritoitem (id, cantidad, producto_id, user_id) FROM stdin;
6	6	3	3
7	2	4	3
\.


--
-- Data for Name: productos_categoria; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.productos_categoria (id, nombre, descripcion) FROM stdin;
3	Subproductos	Derivados tales como cera, polen o veneno.
2	Medicinas	Productos terapeuticos y con alto valor medicinal.
4	Insumos	Materiales y herramientas.
5	Material biológico	Activos tales como reinas o colmenas completas.
1	Alimentos	Productos para el consumo.
\.


--
-- Data for Name: productos_cupon; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.productos_cupon (id, codigo, descuento_porcentaje, descuento_valor, activo) FROM stdin;
1	BIENVENIDO10	10	0.00	t
2	MIEL5000	0	5000.00	t
\.


--
-- Data for Name: productos_galeria; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.productos_galeria (id, imagen, caption, likes, comments, link, created_at) FROM stdin;
1	galeria/imagenPerfilInstagramCard.jpeg	Perfil Instagram	0	0	https://www.instagram.com/api4reinas/	2026-06-24 03:48:39.409878+00
2	galeria/avellano.jpg	avellano	0	0		2026-06-26 17:44:54.551483+00
3	galeria/barbaAbejas.jpg	Barbaabejas	0	0		2026-06-26 19:57:25.782891+00
4	galeria/propoleo_gemini.png	Propoleo gemini	0	0		2026-06-26 19:57:25.786488+00
5	galeria/cajones_gemini.png	Cajones gemini	0	0		2026-06-26 19:57:25.788191+00
6	galeria/yoSostengoMarco.jpg	Yosostengomarco	0	0		2026-06-26 19:57:25.790368+00
7	galeria/flores-abejas.jpg	Flores-abejas	0	0		2026-06-26 19:57:25.791737+00
8	galeria/panal.jpg	Panal	0	0		2026-06-26 19:57:25.793958+00
9	galeria/comportamientos_De_las_Abejas_1ok.jpg	Comportamientos de las abejas 1ok	0	0		2026-06-26 19:57:25.795603+00
10	galeria/panales_miel_gemini.png	Panales miel gemini	0	0		2026-06-26 19:57:25.796874+00
11	galeria/miel_gemini.png	Miel gemini	0	0		2026-06-26 19:57:25.797712+00
12	galeria/sombrero.jpg	Sombrero	0	0		2026-06-26 19:57:25.798559+00
13	galeria/caballete.jpg	Caballete	0	0		2026-06-26 19:57:25.799197+00
14	galeria/lavanda.jpg	Lavanda	0	0		2026-06-26 19:57:25.799921+00
15	galeria/apiario.jpg	Apiario	0	0		2026-06-26 19:57:25.800608+00
16	galeria/abejaEnCerezo.jpg	Abejaencerezo	0	0		2026-06-26 19:57:25.801398+00
17	galeria/envasesMiel.JPG	Envasesmiel	0	0		2026-06-26 19:57:25.802146+00
18	galeria/perritos.jpg	Perritos	0	0		2026-06-26 19:57:25.802737+00
19	galeria/mielMano.jpg	Mielmano	0	0		2026-06-26 19:57:25.803351+00
20	galeria/quillay3.jpg	Quillay3	0	0		2026-06-26 19:57:25.804143+00
21	galeria/caballetes_gemini.png	Caballetes gemini	0	0		2026-06-26 19:57:25.80516+00
22	galeria/magnolio.HEIC	Magnolio	0	0		2026-06-26 19:57:25.80588+00
\.


--
-- Data for Name: productos_itempedido; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.productos_itempedido (id, nombre_producto, precio, cantidad, producto_id, pedido_id) FROM stdin;
1	Miel 500 g	2500.00	1	3	1
2	Miel 500 g	2500.00	1	3	2
3	Miel 265 g	2000.00	3	4	3
\.


--
-- Data for Name: productos_pedido; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.productos_pedido (id, nombre_completo, email, telefono, direccion, ciudad, metodo_pago, total, estado, created_at, updated_at, user_id) FROM stdin;
1	Jose Veloso Inzunza	josevin09@gmail.com	+56956110251	Ruta 5 Sur Km 521 Sector Miramar Parcela 7	Los Ángeles	webpay	5750.00	pendiente	2026-06-26 07:52:50.878413+00	2026-06-26 07:52:50.878483+00	\N
2	Jose Veloso Inzunza	josevin09@gmail.com	+56956110251	Ruta 5 Sur Km 521 Sector Miramar Parcela 7	Los Ángeles	webpay	3500.00	pendiente	2026-06-26 07:56:50.448113+00	2026-06-26 07:56:50.448198+00	3
3	Jose Veloso Inzunza	josevin09@gmail.com	+56956110251	Ruta 5 Sur Km 521 Sector Miramar Parcela 7	Los Ángeles	webpay	9500.00	pendiente	2026-06-26 08:03:52.723347+00	2026-06-26 08:03:52.723425+00	\N
\.


--
-- Data for Name: productos_perfilusuario; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.productos_perfilusuario (id, rut, telefono, direccion, ciudad, user_id) FROM stdin;
1	19.600.494-7	+56956110251	Ruta 5 Sur Km 521 Sector Miramar Parcela 7	Los Ángeles	3
\.


--
-- Data for Name: productos_perfilusuario_cupones; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.productos_perfilusuario_cupones (id, perfilusuario_id, cupon_id) FROM stdin;
1	1	2
\.


--
-- Data for Name: productos_producto; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.productos_producto (id, nombre, descripcion, precio, stock, categoria_id, created_at, imagen, updated_at) FROM stdin;
6	Miel en panal 200 g	Miel 100% cruda y natural presentada en su panal original de cera. Sin procesos ni filtrados: de la colmena a tu mesa, perfecto para desayunos, postres y tablas de picoteo. Formato 200 g.	6500.00	0	1	2026-06-15 02:28:51.782148+00	productos/panales_miel_gemini.png	2026-06-15 22:08:15.000269+00
5	Propoleo en gotas 15 mL	Tinta de propoleo en gotas al 10% de concentración formato 15 mL con gotario incluido.	6000.00	0	2	2026-06-14 05:38:30.222964+00	productos/propoleo_gemini.png	2026-06-15 22:08:25.235917+00
3	Miel 500 g	Miel cruda multifloral con alto contenido de Quillay y flores nativas en formato de 500 g.	2500.00	15	1	2026-06-14 05:28:36.554183+00	productos/miel500g.png	2026-06-15 22:09:01.705578+00
4	Miel 265 g	Miel cruda multifloral con alto contenido de Quillay y flores nativas en formato de 265 g.	2000.00	8	1	2026-06-14 05:30:40.367971+00	productos/miel265g.png	2026-06-15 22:09:08.690316+00
7	Caballete o base	Base con altura de 49 cm de alto y un 2 % de inclinación, permite una altura adecuada para trabajar y una inclinación adecuada para evitar que ingrese agua por las piqueras.	20000.00	0	4	2026-06-15 21:57:46.267156+00	productos/caballete.jpg	2026-06-25 21:20:52.770716+00
8	Cámara de cria	Cámara de cria tipo Langstroth completa con techo de zinc, entretapa, alza, 10 marcos y piso.	50000.00	0	4	2026-06-15 22:02:07.23417+00	productos/camaraCria.png	2026-06-25 21:44:04.638254+00
2	Miel 1 Kg	Miel cruda multifloral con alto contenido de Quillay y flores nativas en formato de 1 Kg.	4000.00	0	1	2026-06-13 00:10:23.811489+00	productos/miel1kg.png	2026-06-25 23:49:13.250492+00
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 64, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 3, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 41, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 16, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 28, true);


--
-- Name: productos_carritoitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.productos_carritoitem_id_seq', 7, true);


--
-- Name: productos_categoria_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.productos_categoria_id_seq', 5, true);


--
-- Name: productos_cupon_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.productos_cupon_id_seq', 2, true);


--
-- Name: productos_galeria_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.productos_galeria_id_seq', 22, true);


--
-- Name: productos_itempedido_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.productos_itempedido_id_seq', 3, true);


--
-- Name: productos_pedido_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.productos_pedido_id_seq', 3, true);


--
-- Name: productos_perfilusuario_cupones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.productos_perfilusuario_cupones_id_seq', 1, true);


--
-- Name: productos_perfilusuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.productos_perfilusuario_id_seq', 1, true);


--
-- Name: productos_producto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.productos_producto_id_seq', 8, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: productos_carritoitem productos_carritoitem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_carritoitem
    ADD CONSTRAINT productos_carritoitem_pkey PRIMARY KEY (id);


--
-- Name: productos_carritoitem productos_carritoitem_user_id_producto_id_9e7f51f3_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_carritoitem
    ADD CONSTRAINT productos_carritoitem_user_id_producto_id_9e7f51f3_uniq UNIQUE (user_id, producto_id);


--
-- Name: productos_categoria productos_categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_categoria
    ADD CONSTRAINT productos_categoria_pkey PRIMARY KEY (id);


--
-- Name: productos_cupon productos_cupon_codigo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_cupon
    ADD CONSTRAINT productos_cupon_codigo_key UNIQUE (codigo);


--
-- Name: productos_cupon productos_cupon_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_cupon
    ADD CONSTRAINT productos_cupon_pkey PRIMARY KEY (id);


--
-- Name: productos_galeria productos_galeria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_galeria
    ADD CONSTRAINT productos_galeria_pkey PRIMARY KEY (id);


--
-- Name: productos_itempedido productos_itempedido_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_itempedido
    ADD CONSTRAINT productos_itempedido_pkey PRIMARY KEY (id);


--
-- Name: productos_pedido productos_pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_pedido
    ADD CONSTRAINT productos_pedido_pkey PRIMARY KEY (id);


--
-- Name: productos_perfilusuario_cupones productos_perfilusuario__perfilusuario_id_cupon_i_a610fdb4_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_perfilusuario_cupones
    ADD CONSTRAINT productos_perfilusuario__perfilusuario_id_cupon_i_a610fdb4_uniq UNIQUE (perfilusuario_id, cupon_id);


--
-- Name: productos_perfilusuario_cupones productos_perfilusuario_cupones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_perfilusuario_cupones
    ADD CONSTRAINT productos_perfilusuario_cupones_pkey PRIMARY KEY (id);


--
-- Name: productos_perfilusuario productos_perfilusuario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_perfilusuario
    ADD CONSTRAINT productos_perfilusuario_pkey PRIMARY KEY (id);


--
-- Name: productos_perfilusuario productos_perfilusuario_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_perfilusuario
    ADD CONSTRAINT productos_perfilusuario_user_id_key UNIQUE (user_id);


--
-- Name: productos_producto productos_producto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_producto
    ADD CONSTRAINT productos_producto_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: productos_carritoitem_producto_id_a8bcfc62; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX productos_carritoitem_producto_id_a8bcfc62 ON public.productos_carritoitem USING btree (producto_id);


--
-- Name: productos_carritoitem_user_id_4fdd23f0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX productos_carritoitem_user_id_4fdd23f0 ON public.productos_carritoitem USING btree (user_id);


--
-- Name: productos_cupon_codigo_4ef86182_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX productos_cupon_codigo_4ef86182_like ON public.productos_cupon USING btree (codigo varchar_pattern_ops);


--
-- Name: productos_itempedido_pedido_id_06d4f5eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX productos_itempedido_pedido_id_06d4f5eb ON public.productos_itempedido USING btree (pedido_id);


--
-- Name: productos_itempedido_producto_id_cc7f2b2b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX productos_itempedido_producto_id_cc7f2b2b ON public.productos_itempedido USING btree (producto_id);


--
-- Name: productos_pedido_user_id_3f67de26; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX productos_pedido_user_id_3f67de26 ON public.productos_pedido USING btree (user_id);


--
-- Name: productos_perfilusuario_cupones_cupon_id_c6533254; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX productos_perfilusuario_cupones_cupon_id_c6533254 ON public.productos_perfilusuario_cupones USING btree (cupon_id);


--
-- Name: productos_perfilusuario_cupones_perfilusuario_id_b76c35c4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX productos_perfilusuario_cupones_perfilusuario_id_b76c35c4 ON public.productos_perfilusuario_cupones USING btree (perfilusuario_id);


--
-- Name: productos_producto_categoria_id_1fef506a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX productos_producto_categoria_id_1fef506a ON public.productos_producto USING btree (categoria_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: productos_carritoitem productos_carritoite_producto_id_a8bcfc62_fk_productos; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_carritoitem
    ADD CONSTRAINT productos_carritoite_producto_id_a8bcfc62_fk_productos FOREIGN KEY (producto_id) REFERENCES public.productos_producto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: productos_carritoitem productos_carritoitem_user_id_4fdd23f0_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_carritoitem
    ADD CONSTRAINT productos_carritoitem_user_id_4fdd23f0_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: productos_itempedido productos_itempedido_pedido_id_06d4f5eb_fk_productos_pedido_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_itempedido
    ADD CONSTRAINT productos_itempedido_pedido_id_06d4f5eb_fk_productos_pedido_id FOREIGN KEY (pedido_id) REFERENCES public.productos_pedido(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: productos_itempedido productos_itempedido_producto_id_cc7f2b2b_fk_productos; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_itempedido
    ADD CONSTRAINT productos_itempedido_producto_id_cc7f2b2b_fk_productos FOREIGN KEY (producto_id) REFERENCES public.productos_producto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: productos_pedido productos_pedido_user_id_3f67de26_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_pedido
    ADD CONSTRAINT productos_pedido_user_id_3f67de26_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: productos_perfilusuario_cupones productos_perfilusua_cupon_id_c6533254_fk_productos; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_perfilusuario_cupones
    ADD CONSTRAINT productos_perfilusua_cupon_id_c6533254_fk_productos FOREIGN KEY (cupon_id) REFERENCES public.productos_cupon(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: productos_perfilusuario_cupones productos_perfilusua_perfilusuario_id_b76c35c4_fk_productos; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_perfilusuario_cupones
    ADD CONSTRAINT productos_perfilusua_perfilusuario_id_b76c35c4_fk_productos FOREIGN KEY (perfilusuario_id) REFERENCES public.productos_perfilusuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: productos_perfilusuario productos_perfilusuario_user_id_edddc272_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_perfilusuario
    ADD CONSTRAINT productos_perfilusuario_user_id_edddc272_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: productos_producto productos_producto_categoria_id_1fef506a_fk_productos; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_producto
    ADD CONSTRAINT productos_producto_categoria_id_1fef506a_fk_productos FOREIGN KEY (categoria_id) REFERENCES public.productos_categoria(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict NDmkMj4xtp4iAhlMvdWj4tDm3emcvrS2AjbQFd5MCgYtQy8SStMgjlkdEE5fNFc

