steps:
  # Paso 1: Construir la imagen desde la carpeta backend
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA', '.']

  # Paso 2: Subir la imagen a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA']

  # Paso 3: Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'backend'
      - '--image=gcr.io/$PROJECT_ID/backend:$COMMIT_SHA'
      - '--region=southamerica-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=apicuatroreinas:southamerica-west1:bd4reinas2'
      - '--set-env-vars=INSTANCE_CONNECTION_NAME=apicuatroreinas:southamerica-west1:bd4reinas2,DB_NAME=postgres,DB_USER=postgres,EMAIL_HOST=pro.eu.turbo-smtp.com,EMAIL_PORT=587,EMAIL_USE_TLS=True,EMAIL_USE_SSL=False,DEFAULT_FROM_EMAIL=apicuatroreinas@gmail.com,CONTACT_RECIPIENT_EMAIL=joseveloso2101@gmail.com'
      - '--set-secrets=SECRET_KEY=django-secret-key:latest,DB_PASSWORD=db-password:latest,EMAIL_HOST_USER=smtp-username:latest,EMAIL_HOST_PASSWORD=smtp-password:latest'

images:
  - 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
