# Generated by Django 5.2.15 on 2026-06-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_created_at_producto_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('caption', models.TextField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('link', models.URLField(default='https://www.instagram.com/api4reinas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
