# Generated by Django 5.2.15 on 2026-06-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_carritoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
