# Generated by Django 5.2.6 on 2026-07-20 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_pedido_cupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de perfil')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografía')),
                ('cantidad_posts', models.PositiveIntegerField(default=0, verbose_name='Cantidad de posts')),
                ('cantidad_seguidores', models.PositiveIntegerField(default=0, verbose_name='Cantidad de seguidores')),
                ('cantidad_seguidos', models.PositiveIntegerField(default=0, verbose_name='Cantidad de seguidos')),
                ('imagen_perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_avatar_instagram', to='productos.galeria', verbose_name='Imagen de perfil (desde Galería)')),
            ],
            options={
                'verbose_name': 'Perfil de Instagram',
                'verbose_name_plural': 'Perfiles de Instagram',
            },
        ),
        migrations.CreateModel(
            name='InstagramPerfilPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.PositiveIntegerField(default=0, verbose_name='Índice de antigüedad (orden)')),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_publicaciones', to='productos.galeria', verbose_name='Publicación (desde Galería)')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='productos.instagramperfil', verbose_name='Perfil de Instagram')),
            ],
            options={
                'verbose_name': 'Publicación de Perfil',
                'verbose_name_plural': 'Publicaciones de Perfil',
                'ordering': ['indice'],
                'unique_together': {('perfil', 'galeria')},
            },
        ),
    ]
